#!/bin/bash
#PBS -N julia_job
#PBS -q normal
#PBS -l select=1:ncpus=128:mem=200GB:model=mil_ait
#PBS -l walltime=4:00:00
#PBS -o /nobackup/avaliyap/logs/output_m.out
#PBS -e /nobackup/avaliyap/logs/output_m.err


export PATH="/home3/avaliyap/.juliaup/bin:$PATH"
source ~/.bashrc
export JULIA_NUM_THREADS=128


JULIA_CONFIG=/home3/avaliyap/Documents/Julia_new/Julia/config/run_hpc.toml \
julia ${JULIA_SCRIPT}




