#!/bin/bash
#PBS -N niw_filter
#PBS -q normal
#PBS -l select=1:ncpus=128:mem=200GB:model=mil_ait
#PBS -l walltime=3:00:00
#PBS -o /nobackup/avaliyap/logs/output.out
#PBS -e /nobackup/avaliyap/logs/output.err


export PATH="/home3/avaliyap/.juliaup/bin:$PATH"


export JULIA_NUM_THREADS=128


JULIA_CONFIG=/home3/avaliyap/Documents/Julia_new/Julia/config/run_hpc.toml \
julia /home3/avaliyap/Documents/Julia_new/Julia/Codes/V2/tiling.jl




