#!/bin/bash
#PBS -N niw_filter
#PBS -q devel
#PBS -l select=1:ncpus=16:mem=80GB
#PBS -l walltime=02:00:00
#PBS -o /nobackup/avaliyap/logs/output.out
#PBS -e /nobackup/avaliyap/logs/output.err


export PATH="/home3/avaliyap/.juliaup/bin:$PATH"
source "/home3/avaliyap/.juliaup/env"


export JULIA_NUM_THREADS=16


JULIA_CONFIG=/home3/avaliyap/Documents/Julia_new/Julia/config/run_hpc.toml \
julia /home3/avaliyap/Documents/Julia_new/Julia/Codes/Budget/NIW/UVW_bpfilter.jl




